name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *' # Once per day at 10am UTC

jobs:
  ubuntu:
    name: Test on Ubuntu
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp: ["24", "25", "26"]
      fail-fast: false

    container:
      image: erlang:${{ matrix.otp }}

    env:
      ERL_LIBS: './'

    steps:
      - uses: actions/checkout@v4
      - name: Checkout Proper
        uses: actions/checkout@v4
        with:
          repository: proper-testing/proper
          path: "./proper"
      - name: Run test
        run: |
          make
          make tests

  macos:
    name: Test on MacOS
    runs-on: macos-latest

    strategy:
      matrix:
        otp: ["24", "25", "26"]
      fail-fast: false

    env:
      ERL_LIBS: './'

    steps:
      - uses: actions/checkout@v4
      - name: Brew Version Check
        run: brew --version
      - name: Keep Brew Fresh
        run: brew update
      - name: Install Erlang
        run: brew install erlang@${{ matrix.otp }}
      - name: Brew Link
        run: brew link erlang@${{ matrix.otp }} --force
      - name: Checkout Proper
        uses: actions/checkout@v4
        with:
          repository: proper-testing/proper
          path: "./proper"
      - name: Run test
        run: |
          make
          make tests
