name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ubuntu:
    name: Test on Ubuntu
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp: ["23", "24"]
      fail-fast: false

    container:
      image: erlang:${{ matrix.otp }}

    env:
      ERL_LIBS: './'

    steps:
      - uses: actions/checkout@v2
      - name: Checkout Proper
        uses: actions/checkout@v2
        with:
          repository: proper-testing/proper
          path: "./proper"
      - name: Run test
        run: |
          make
          make tests
